/**
 * @file audio_input.cpp
 * @brief Audio input implementation — I2S (new driver) for PCM1808
 */

#include "audio_input.h"

void AudioInput::init(int32_t sampleRate, int32_t numChannels) {
    _sampleRate  = sampleRate;
    _numChannels = numChannels;

    initI2SInput();
}

void AudioInput::initI2SInput() {
    // --- Channel config ---
    // Role = SLAVE because BCK/WS are shared with the output port (I2S_NUM_0)
    // which is MASTER and already drives those lines.
    // Two MASTER ports on the same BCK/WS = clock conflict → noise/corruption!
    i2s_chan_config_t m_rx_chan_cfg = {};
    m_rx_chan_cfg.id            = I2S_INPUT_PORT;
    m_rx_chan_cfg.role          = I2S_ROLE_SLAVE;
    m_rx_chan_cfg.dma_desc_num  = 8;
    m_rx_chan_cfg.dma_frame_num = DSP_FRAME_SIZE;
    m_rx_chan_cfg.auto_clear_after_cb  = true;
    m_rx_chan_cfg.auto_clear_before_cb = false;

    // Allocate RX channel only (tx = NULL)
    ESP_ERROR_CHECK(i2s_new_channel(&m_rx_chan_cfg, NULL, &_rxHandle));

    // --- Standard I2S mode config ---
    i2s_std_config_t m_rx_std_cfg = {};

    // Philips/standard I2S: 32-bit stereo
    // PCM1808 xuất 24-bit left-justified trong frame 32-bit (8 bit thấp = 0)
    m_rx_std_cfg.slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
        I2S_DATA_BIT_WIDTH_32BIT,
        I2S_SLOT_MODE_STEREO
    );

    // Pin mapping
    // MCLK is generated by the output (MASTER) port. Set to UNUSED here to avoid conflict.
    m_rx_std_cfg.gpio_cfg.mclk  = I2S_GPIO_UNUSED;
    m_rx_std_cfg.gpio_cfg.bclk  = (gpio_num_t)I2S_IN_BCK_PIN;   // GPIO26 — chung với output
    m_rx_std_cfg.gpio_cfg.ws    = (gpio_num_t)I2S_IN_WS_PIN;    // GPIO25 — chung với output
    m_rx_std_cfg.gpio_cfg.din   = (gpio_num_t)I2S_IN_DATA_PIN;  // GPIO35 — DOUT của PCM1808
    m_rx_std_cfg.gpio_cfg.dout  = I2S_GPIO_UNUSED;
    m_rx_std_cfg.gpio_cfg.invert_flags.mclk_inv = false;
    m_rx_std_cfg.gpio_cfg.invert_flags.bclk_inv = false;
    m_rx_std_cfg.gpio_cfg.invert_flags.ws_inv   = false;

    // Clock — MCLK = 512 * fs (PCM1808 slave mode yêu cầu SCK liên tục)
    m_rx_std_cfg.clk_cfg.sample_rate_hz = (uint32_t)_sampleRate;
    m_rx_std_cfg.clk_cfg.clk_src        = I2S_CLK_SRC_DEFAULT;
    m_rx_std_cfg.clk_cfg.mclk_multiple  = I2S_MCLK_MULTIPLE_512; // 512x MCLK to ensure accurate sample rates with 24-bit data

    ESP_ERROR_CHECK(i2s_channel_init_std_mode(_rxHandle, &m_rx_std_cfg));
    ESP_ERROR_CHECK(i2s_channel_enable(_rxHandle));
}

// ---------------------------------------------------------------------------

size_t AudioInput::readFrame(float* __restrict buffer, size_t numSamples) {
    return readI2S(buffer, numSamples);
}

size_t IRAM_ATTR AudioInput::readI2S(float* __restrict buffer, size_t numSamples) {
    const size_t totalSamples = numSamples * _numChannels;
    if (totalSamples > DSP_FRAME_SAMPLES) return 0;

    size_t bytesRead   = 0;

    int32_t buf_to_read[DSP_FRAME_SAMPLES]; // Max frame size in samples (interleaved)
    esp_err_t err = i2s_channel_read(_rxHandle, buf_to_read, totalSamples * sizeof(int32_t),
                                     &bytesRead, portMAX_DELAY);
    if (err != ESP_OK) return 0;

    const size_t samplesRead = bytesRead / sizeof(int32_t);
    for (size_t i = 0; i < samplesRead; i++) {
        // Convert signed 32-bit PCM to float in [-1, 1)
        buffer[i] = (float)buf_to_read[i] / 2147483648.0f;
    }

    return bytesRead / (sizeof(int32_t) * _numChannels);
}
